name: CI


on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  
  build-macos:
    name: 使用macOS构建
    runs-on: macos-latest
    env:
        JOB_TYPE: BUILD

    steps:
      
      - uses: actions/checkout@v2

      - name: 安装依赖环境
        run: brew install flex bison

      - name: 开始构建工具
        run: |
          make clean
          ./unixbuild.sh
      - name: 打包上传工作件
        uses: actions/upload-artifact@v2
        with:
          name: acpica_macOS_build
          path: Darwin/*.zip
  
      - name: 上传发布版本
        if: github.event_name == 'release'
        uses: wy414012/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Darwin/*.zip
          tag: ${{ github.ref }}
          file_glob: true
          
  build-linux:
    name: linux-gcc构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 安装依赖环境
        run: |
          sudo apt-get update
          sudo apt-get install flex bison

      - name: 开始构建工具
        run: |
          make clean
          ./unixbuild.sh

      - name: 打包上传构建工件
        uses: actions/upload-artifact@v2
        with:
          name: acpica_Linux_build
          path: Linux/*.zip

      - name: 上传发布版本
        if: github.event_name == 'release'
        uses: wy414012/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Linux/*.zip
          tag: ${{ github.ref }}
          file_glob: true
          
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build ACPICA
      run: |
        cd ${{ github.workspace }}/source/tools/acpica
        msbuild /m /t:rebuild /p:Configuration=Release /p:Platform="x64"
